CREATE TABLE [dbo].[receivedData] (
    [runGuid]                 UNIQUEIDENTIFIER NULL,
    [runTime]                 DATETIME         NULL,
    [icon]                    NVARCHAR (50)    NULL,
    [summary]                 NVARCHAR (500)   NULL,
    [RcvWindSpeed]            VARCHAR (6)      NULL,
    [RcvWindGust]             VARCHAR (6)      NULL,
    [RcvWindBearing]          VARCHAR (6)      NULL,
    [RcvTemperature]          VARCHAR (6)      NULL,
    [RcvApparentTemperature]  VARCHAR (6)      NULL,
    [RcvprecipIntensity]      VARCHAR (6)      NULL,
    [RcvprecipIntensityError] VARCHAR (60)     NULL,
    [RcvprecipProbability]    VARCHAR (6)      NULL,
    [precipType]              VARCHAR (6)      NULL,
    [RcvNearestStormDistance] VARCHAR (6)      NULL,
    [RcvDewPoint]             VARCHAR (6)      NULL,
    [RcvHumidity]             VARCHAR (6)      NULL,
    [RcvPressure]             VARCHAR (6)      NULL,
    [RcvCloudCover]           VARCHAR (6)      NULL,
    [RcvuvIndex]              VARCHAR (6)      NULL,
    [RcvVisibility]           VARCHAR (6)      NULL,
    [RcvOzone]                VARCHAR (6)      NULL,
    [runID]                   INT              NOT NULL, 
    CONSTRAINT [PK_receivedData_runID] PRIMARY KEY ([runID])
);

